const routes = {
  home: '/',
  minimal: '/minimal',
  retro: '/retro',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notifications',
  vote: '/vote',
  payLinks: '/paylink',
  createPayLink: '/paylink/new',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  classic: '/classic',
  products: '/products',
  integrations: '/integrations',
  createProduct: '/products/new',
  merchantSettings: '/merchant-settings',
};

export default routes;
